spring:
  output:
    ansi:
      enabled: always

format:
  date-time: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

logging:
  level:
    org:
      springframework: INFO
    app:
      netlify:
        nmhillusion: DEBUG